name: Build Expo Web App

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Expo Web
        run: npx expo export:web

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: limitless-web
          path: dist
