name: Build Flutter Web App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Build Flutter Web
      run: flutter build web --release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: limitless-web
        path: build/web
